### PR TITLE
don't fail on missing dir for clean

### PR DESCRIPTION
**Pull request by evanmcc**
@JayKickliter does this look right?

### CODE REVIEW

**Comment by evanmcc** [comment]
```erlang-h3$ rebar3 clean
===> Fetching covertool v2.0.2
===> Version cached at .cache/rebar3/hex/hexpm/packages/covertool-2.0.2.tar is up to date, reusing it
===> Compiling covertool
===> Verifying dependencies...
===> Cleaning out h3...
Error: erlang-h3/_build/c_src is not a directory
Error: erlang-h3/_build/c_src is not a directory
erlang-h3$ echo $?
0
```

**Comment by JayKickliter** [comment]
My initial though would have been to test for the existence of the directory then call cmake, but if that works then go ahead.

**Comment by evanmcc** [comment]
I tried a couple of different ways to check, but I can't seem to get it to work. do you have any ideas?

**Comment by JayKickliter** [comment]
`rm -rf _build/c_src`?

**Comment by JayKickliter** [comment]
~I forget, how do you get it into the state where this is a problem?~

Disregard, just running `./rebar3 clean` without compiling first triggers the problem.

**Review by JayKickliter — APPROVED** [review]

**Pull request merged**
